version: "3.8"

services:
  wishlist-api:
    depends_on:
      - mongodb
    build:
      context: ../
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - 8080:8080
      - 5005:5005
    networks:
      - wishlist-api
    environment:
      - FINANCIAL_ALERT_DB_URI=mongodb://mongodb/wishlist-api
      - DATABASE=wishlist-api
      - AUTHENTICATION_DATABASE=authentication-database
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  mongodb:
    image: bitnami/mongodb:latest
    container_name: "mongodb"
    restart: always
    ports:
      - 27017:27017
    networks:
      - wishlist-api
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

networks:
  wishlist-api:
    driver: bridge