spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      authentication-database: ${AUTHENTICATION_DATABASE}
      database: ${DATABASE}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    topics: ${TOPICS}

logging:
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} - requestTraceid=%X{requestTraceId} - %msg%n"

mongock:
  migration-scan-package: com.dev.wishlist.changelogs

springdoc:
  swagger-ui:
    path: /swagger-ui.html